// Generated by gencpp from file ros_arduino_trial/pwm_signal.msg
// DO NOT EDIT!


#ifndef ROS_ARDUINO_TRIAL_MESSAGE_PWM_SIGNAL_H
#define ROS_ARDUINO_TRIAL_MESSAGE_PWM_SIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_arduino_trial
{
template <class ContainerAllocator>
struct pwm_signal_
{
  typedef pwm_signal_<ContainerAllocator> Type;

  pwm_signal_()
    : dir(false)
    , data(0)  {
    }
  pwm_signal_(const ContainerAllocator& _alloc)
    : dir(false)
    , data(0)  {
  (void)_alloc;
    }



   typedef uint8_t _dir_type;
  _dir_type dir;

   typedef uint16_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> const> ConstPtr;

}; // struct pwm_signal_

typedef ::ros_arduino_trial::pwm_signal_<std::allocator<void> > pwm_signal;

typedef boost::shared_ptr< ::ros_arduino_trial::pwm_signal > pwm_signalPtr;
typedef boost::shared_ptr< ::ros_arduino_trial::pwm_signal const> pwm_signalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_arduino_trial::pwm_signal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_arduino_trial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_arduino_trial': ['/home/isabella/catkin_ws/src/rosserial_tutorials/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a874b178257f5432b765c0462992b150";
  }

  static const char* value(const ::ros_arduino_trial::pwm_signal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa874b178257f5432ULL;
  static const uint64_t static_value2 = 0xb765c0462992b150ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_arduino_trial/pwm_signal";
  }

  static const char* value(const ::ros_arduino_trial::pwm_signal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#This is the message file for generating a custom message to control a DC\n\
#motor using MD10C R3 motor driver by Cytron technologies in Sign Magnitude \n\
#mode.\n\
bool dir\n\
uint16 data\n\
";
  }

  static const char* value(const ::ros_arduino_trial::pwm_signal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dir);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pwm_signal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_arduino_trial::pwm_signal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_arduino_trial::pwm_signal_<ContainerAllocator>& v)
  {
    s << indent << "dir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dir);
    s << indent << "data: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ARDUINO_TRIAL_MESSAGE_PWM_SIGNAL_H
